# Generated by Django 2.2.3 on 2020-04-14 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_auto_20200414_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskfile',
            name='agents',
        ),
        migrations.AddField(
            model_name='subtask',
            name='agents',
            field=models.ManyToManyField(related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
    ]
